### PR TITLE
remove requirejs, dont need it with angular, never do so…

### PR DESCRIPTION
**Pull request by sovanna**
…mething like that

### CODE REVIEW

**Comment by darul75** [comment]
a mistake, merci

**Comment by sovanna** [comment]
no problem, sorry for "words" that I used, I was pissed by something else, never mind, i've no excuse.
Thanks anyway ;)

**Comment by darul75** [comment]
you are welcome but next time I kick your fucking ass :)

**Comment by sovanna** [comment]
haha, you are funny, nice dude ;)

**Comment by ballerabdude** [comment]
+1 
@darul75 Can you please merge :)

**Pull request merged**
